DROP DATABASE SoftwareHouse;
CREATE DATABASE SoftwareHouse;
USE SoftwareHouse;
CREATE TABLE Client (
  ClientID INT NOT NULL ,
  FirstName VARCHAR(255) NOT NULL,
  LastName VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL,
  Phone VARCHAR(255) NOT NULL,
  Address VARCHAR(255) NOT NULL,
  PRIMARY KEY (ClientID)
);

CREATE TABLE Employee (
  EmployeeID INT NOT NULL ,
  FirstName VARCHAR(255) NOT NULL,
  LastName VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL,
  Phone VARCHAR(255) NOT NULL,
  Address VARCHAR(255) NOT NULL,
  HireDate DATE NOT NULL,
  Salary INT NOT NULL,
  PRIMARY KEY (EmployeeID)
);

CREATE TABLE Project (
  ProjectID INT NOT NULL ,
  Title VARCHAR(255) NOT NULL,
  Description VARCHAR(255) NOT NULL,
  StartDate DATE NOT NULL,
  EndDate DATE NOT NULL,
  ClientID INT NOT NULL,
  PRIMARY KEY (ProjectID)
);

CREATE TABLE Task (
  TaskID INT NOT NULL ,
  Description VARCHAR(255) NOT NULL,
  StartDate DATE NOT NULL,
  EndDate DATE NOT NULL,
  ProjectID INT NOT NULL,
  EmployeeID INT NOT NULL,
  PRIMARY KEY (TaskID)
);

CREATE TABLE Service (
  ServiceID INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL,
  Description VARCHAR(255) NOT NULL,
  PRIMARY KEY (ServiceID)
);

CREATE TABLE Contract (
  ContractID INT NOT NULL ,
  ServiceID INT NOT NULL,
  ClientID INT NOT NULL,
  EmployeeID INT NOT NULL,
  StartDate DATE NOT NULL,
  EndDate DATE NOT NULL,
  TermsAndConditions VARCHAR(255) NOT NULL,
  PRIMARY KEY (ContractID)
);

CREATE TABLE Payment (
  PaymentID INT NOT NULL ,
  ContractID INT NOT NULL,
  Amount INT NOT NULL,
  PaymentDate DATE NOT NULL,
  PRIMARY KEY (PaymentID)
);

ALTER TABLE Project
ADD CONSTRAINT FK_Project_ClientID
FOREIGN KEY (ClientID) REFERENCES Client (ClientID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Task
ADD CONSTRAINT FK_Task_ProjectID
FOREIGN KEY (ProjectID) REFERENCES Project (ProjectID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Task
ADD CONSTRAINT FK_Task_EmployeeID
FOREIGN KEY (EmployeeID) REFERENCES Employee (EmployeeID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Contract
ADD CONSTRAINT FK_Contract_ServiceID
FOREIGN KEY (ServiceID) REFERENCES Service (ServiceID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Contract
ADD CONSTRAINT FK_Contract_ClientID
FOREIGN KEY (ClientID) REFERENCES Client (ClientID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Contract
ADD CONSTRAINT FK_Contract_EmployeeID
FOREIGN KEY (EmployeeID) REFERENCES Employee (EmployeeID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Payment
ADD CONSTRAINT FK_Payment_ContractID
FOREIGN KEY (ContractID) REFERENCES Contract (ContractID)
ON DELETE CASCADE
ON UPDATE CASCADE;


